# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: Donlund/Hjemmeside-for-Katrine
  branch: main
  identity_url: https://auth.decapbridge.com/sites/e4016aee-c449-456a-a1ec-ecf2d8118247
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://healerkatrine.netlify.app


media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "indhold"
    label: "Indhold"
    files:
      - file: "content/om.md"
        label: "Om mig"
        name: "om"
        fields:
          - { label: "Indhold", name: "body", widget: "markdown" }
      - file: "content/energi.md"
        label: "Alt er energi"
        name: "energi"
        fields:
          - { label: "Indhold", name: "body", widget: "markdown" }
      - file: "content/ydelser.md"
        label: "Ydelser"
        name: "ydelser"
        fields:
          - { label: "Indhold", name: "body", widget: "markdown" }
      - file: "content/sprays.md"
        label: "Energi Sprays"
        name: "sprays"
        fields:
          - { label: "Indhold", name: "body", widget: "markdown" }
      - file: "content/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - { label: "Indhold", name: "body", widget: "markdown" }
